safe:        false
baseurl:     /
lang:        [en, ja]
future:      false

destination: ./_site
lsi:         false
highlighter: pygments
markdown:    redcarpet
permalink:   /:categories/blog/:year/:month/:day/:title/

default_update_policy:
  page:     "{% if page.raw.modified %}1{% endif %}"
  post:     "{% if page.raw.modified or page.previous.raw.yaml_modified or page.next.raw.yaml_modified %}1{% endif %}"

redcarpet:
  extensions: [autolink, tables]

exclude:     [_tmp, Gruntfile.js, package.json, node_modules]

locale:
  ja:
    locale: ja_JP
    date: "%Y年%m月%d日"

    site_name: てっく煮
    blog_name: てっく煮ブログ

    profile.name: nitoyon (にとよん)
    profile.text: 京都のベンチャー会社勤務。プログラマ、たまに趣味でデザイン。
    profile.more: 詳細

    post.history: 編集履歴
    post.seealso: 関連する記事
    post.toc: 目次

    tag.title: タグ「$0」の記事一覧
    tag.list: タグ一覧に戻る
    tags.title: タグ一覧
    archive.title.year: '%Y年の記事一覧'
    archive.title.month: '%Y年%m月の記事一覧'
    archive.title.day: '%Y年%m月%d日の記事一覧'

    # タグ
    tech-ni: てっく煮
    hatena: はてな
    game: ゲーム
    neta: ネタ
    life: 生活
    math: 数学
    nenga: 年賀状
    book: 書籍
    visualize: ビジュアライズ
    algorithm: アルゴリズム
    study: 勉強会
    hatebu-nenkan: はてブ年鑑
    movie: 動画
    presentation: 発表資料
    release: 作った
    webfonts: 'Web フォント'
    webdesign: 'Web デザイン'
    security: セキュリティー

  en:
    locale: en_US
    date: "%d %b %Y"

    site_name: TECH-NI
    blog_name: TECH-NI Blog

    tag.list: Back to tag list

    profile.name: nitoyon
    profile.text: I'm a programmer in Japan, Kyoto.
    profile.more: more

    post.history: View history
    post.seealso: Related Entries
    post.toc: Table of Contents
