# Base configuration file
# lang property should be defined by child config.
#
# To build Japanese page, specify --config option as follows:
# > jekyll build --config _config.yml,_config.[lang].yml

safe:        false
future:      false

markdown:    redcarpet
permalink:   /en/blog/:year/:month/:day/:title/
basedir:     /en/blog/

redcarpet:
  extensions:
    - autolink
    - tables

sass:
  style:     :compact
  compass:   true
