safe:        false
baseurl:     /
lang:        [en, ja]
#lang:        [en]

destination: ./_site
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /:categories/blog/:year/:month/:day/:title/

default_update_policy:
  page:     "{% if page.raw.modified %}1{% endif %}"
  post:     "{% if page.raw.modified or page.previous.raw.yaml_modified or page.next.raw.yaml_modified %}1{% endif %}"

exclude:     _tmp