safe:        false
baseurl:     /
#lang:        [en, ja]
lang:        [en]

destination: ./_site
lsi:         false
pygments:    true
markdown:    maruku
permalink:   /:categories/blog/:year/:month/:day/:title/

exclude:     _tmp